"""create whatever table

Revision ID: 1a81d095b878
Revises: 
Create Date: 2023-05-27 19:28:14.290426

"""
from alembic import op
import sqlalchemy as sa

from litestar.contrib.sqlalchemy.types import GUID


sa.GUID = GUID

# revision identifiers, used by Alembic.
revision = "1a81d095b878"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "whatever",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.GUID(length=16), nullable=False),
        sa.Column("_sentinel", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_whatever")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("whatever")
    # ### end Alembic commands ###
